package com.android.snippets.ui

import androidx.compose.material3.MaterialTheme
import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.graphics.vector.path
import androidx.compose.ui.unit.dp

@Composable
fun SelectIcon(): ImageVector {
    val color = MaterialTheme.colorScheme.onSurface
    return ImageVector.Builder(
        name = "Select",
        defaultWidth = 24.dp,
        defaultHeight = 24.dp,
        viewportWidth = 960f,
        viewportHeight = 960f
    ).path(
        fill = androidx.compose.ui.graphics.SolidColor(color),
        pathFillType = androidx.compose.ui.graphics.PathFillType.NonZero
    ) {
        moveTo(200f, 760f)
        verticalLineToRelative(80f)
        quadToRelative(-33f, 0f, -56.5f, -23.5f)
        reflectiveQuadTo(120f, 760f)
        horizontalLineToRelative(80f)
        close()
        moveToRelative(-80f, -80f)
        verticalLineToRelative(-80f)
        horizontalLineToRelative(80f)
        verticalLineToRelative(80f)
        horizontalLineToRelative(-80f)
        close()
        moveToRelative(0f, -160f)
        verticalLineToRelative(-80f)
        horizontalLineToRelative(80f)
        verticalLineToRelative(80f)
        horizontalLineToRelative(-80f)
        close()
        moveToRelative(0f, -160f)
        verticalLineToRelative(-80f)
        horizontalLineToRelative(80f)
        verticalLineToRelative(80f)
        horizontalLineToRelative(-80f)
        close()
        moveToRelative(80f, -160f)
        horizontalLineToRelative(-80f)
        quadToRelative(0f, -33f, 23.5f, -56.5f)
        reflectiveQuadTo(200f, 120f)
        verticalLineToRelative(80f)
        close()
        moveToRelative(80f, 640f)
        verticalLineToRelative(-80f)
        horizontalLineToRelative(80f)
        verticalLineToRelative(80f)
        horizontalLineToRelative(-80f)
        close()
        moveToRelative(0f, -640f)
        verticalLineToRelative(-80f)
        horizontalLineToRelative(80f)
        verticalLineToRelative(80f)
        horizontalLineToRelative(-80f)
        close()
        moveToRelative(160f, 640f)
        verticalLineToRelative(-80f)
        horizontalLineToRelative(80f)
        verticalLineToRelative(80f)
        horizontalLineToRelative(-80f)
        close()
        moveToRelative(0f, -640f)
        verticalLineToRelative(-80f)
        horizontalLineToRelative(80f)
        verticalLineToRelative(80f)
        horizontalLineToRelative(-80f)
        close()
        moveToRelative(160f, 640f)
        verticalLineToRelative(-80f)
        horizontalLineToRelative(80f)
        verticalLineToRelative(80f)
        horizontalLineToRelative(-80f)
        close()
        moveToRelative(0f, -640f)
        verticalLineToRelative(-80f)
        horizontalLineToRelative(80f)
        verticalLineToRelative(80f)
        horizontalLineToRelative(-80f)
        close()
        moveToRelative(160f, 560f)
        horizontalLineToRelative(80f)
        quadToRelative(0f, 33f, -23.5f, 56.5f)
        reflectiveQuadTo(760f, 840f)
        verticalLineToRelative(-80f)
        close()
        moveToRelative(0f, -80f)
        verticalLineToRelative(-80f)
        horizontalLineToRelative(80f)
        verticalLineToRelative(80f)
        horizontalLineToRelative(-80f)
        close()
        moveToRelative(0f, -160f)
        verticalLineToRelative(-80f)
        horizontalLineToRelative(80f)
        verticalLineToRelative(80f)
        horizontalLineToRelative(-80f)
        close()
        moveToRelative(0f, -160f)
        verticalLineToRelative(-80f)
        horizontalLineToRelative(80f)
        verticalLineToRelative(80f)
        horizontalLineToRelative(-80f)
        close()
        moveToRelative(0f, -160f)
        verticalLineToRelative(-80f)
        quadToRelative(33f, 0f, 56.5f, 23.5f)
        reflectiveQuadTo(840f, 200f)
        horizontalLineToRelative(-80f)
        close()
    }.build()
}
